services:
  frontend:
    image: dutc-io/capstone_frontend:1.0.0 
    ports:
      - "${REACT_PORT:-3000}:3000"
    command: npm run dev 

  backend:
    image: dutc-io/capstone_backend:1.0.0 
    ports:
      - "${STARLETTE_PORT:-8000}:8000"
    command: 
      >- 
      uvicorn  
      api:app
      --host 0.0.0.0 
      --port 8000
      --reload
