services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    environment:
      PYTHONHASHSEED: 0
      VITE_DEVELOPMENT: DEV
    volumes:
        - ./frontend:/app

  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    volumes:
        - ./backend:/app
